config/routes.rb
Rails.application.routes.draw do

  resources :invoice

  devise_for :users

  root 'invoice#index'
  get 'invoice/:id' => 'invoice#show'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/invoice_controller.rb
class InvoiceController < ApplicationController

  def index
  	@user = current_user

  	if @user.nil?
  	  redirect_to new_user_session_path
  	end

  end

  def show

  	@user = current_user

    pdf = InvoicePdf.new(@user, view_context)
    send_data pdf.render, filename:
    "invoice_#{@user.email}.pdf", type: "application/pdf", disposition: 'inline'

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoice_helper.rb
module InvoiceHelper
end

app/views/invoice/index.html.erb
<h1>Download Invoice</h1>

<p>
	<% if @user %>
		<%= @user.email %>
	<% end %>
</p>

<%= link_to "Create Invoice", invoice_path(:id) %>

app/views/invoice/show.html.erb
<h1>Show Invoice</h1>

<%= @pdf  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrawnDeviseExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
	<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
<% end %>

<%= yield %>

</body>
</html>